kind: pipeline
name: default

steps:
  - name: Bump and tag
    image: quay.io/openware/sdk-tools:1.0.0-1288533
    environment:
      BOT_USERNAME: kite-bot
      BOT_NAME: Kite Bot
      BOT_EMAIL: kite-bot@heliostech.fr
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild

  - name: Build container
    image: plugins/gcr
    settings:
      repo: gcr.io/helios-public/heliostech/rubykube-website
      json_key:
        from_secret: rubykube_gcp_creds_base64

trigger:
  event:
    - push
  branch:
    - master
