language: ruby

dist: trusty
sudo: required

services:
  - docker

before_install:
  - gem install bundler
  - . $HOME/.nvm/nvm.sh
  - nvm install 9
  - nvm use 9

install:
  - bundle install --retry 3
  - travis_retry npm install
  - git checkout -f package-lock.json

script:
  - bundle exec middleman build --verbose

deploy:
  provider: script
  script: bash .deploy.sh
  on:
    branch: develop
